version: '3'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./custom-addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo    
    networks:
      - odoo-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com  # Cambia este valor
      - PGADMIN_DEFAULT_PASSWORD=admin           # Cambia este valor
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - odoo-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  odoo-web-data:
  postgres-data:
  pgadmin-data:

networks:
  odoo-network:

